# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nccreateplayer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nccreateplayer.proto',
  package='',
  serialized_pb='\n\x14nccreateplayer.proto\":\n\x0eNcCreatePlayer\x12\x0b\n\x03Sex\x18\x01 \x02(\x05\x12\r\n\x05\x43lazz\x18\x02 \x02(\x05\x12\x0c\n\x04Name\x18\x03 \x02(\t')




_NCCREATEPLAYER = _descriptor.Descriptor(
  name='NcCreatePlayer',
  full_name='NcCreatePlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sex', full_name='NcCreatePlayer.Sex', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Clazz', full_name='NcCreatePlayer.Clazz', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='NcCreatePlayer.Name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['NcCreatePlayer'] = _NCCREATEPLAYER

class NcCreatePlayer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NCCREATEPLAYER

  # @@protoc_insertion_point(class_scope:NcCreatePlayer)


# @@protoc_insertion_point(module_scope)
