# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nclogin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nclogin.proto',
  package='',
  serialized_pb='\n\rnclogin.proto\"A\n\x07NcLogin\x12\x11\n\tAccountId\x18\x01 \x02(\t\x12\x11\n\tSessionId\x18\x02 \x02(\t\x12\x10\n\x08ServerId\x18\x03 \x02(\x05')




_NCLOGIN = _descriptor.Descriptor(
  name='NcLogin',
  full_name='NcLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='NcLogin.AccountId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='NcLogin.SessionId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ServerId', full_name='NcLogin.ServerId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['NcLogin'] = _NCLOGIN

class NcLogin(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NCLOGIN

  # @@protoc_insertion_point(class_scope:NcLogin)


# @@protoc_insertion_point(module_scope)
